# Generated by Django 5.1.7 on 2025-03-18 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LMSCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("suffix_url", models.CharField(max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="common.lmsuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PublicMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("item_id", models.CharField(max_length=64)),
                ("author", models.CharField(max_length=64)),
                ("text", models.TextField(blank=True)),
                ("header", models.TextField(blank=True)),
                ("footer", models.TextField(blank=True)),
                ("sent_at", models.CharField(max_length=64)),
                ("has_attachment", models.BooleanField(default=False)),
                (
                    "attachment_name",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "attachment_link",
                    models.CharField(blank=True, max_length=256),
                ),
                ("is_exercise", models.BooleanField(default=False)),
                ("is_exercise_finished", models.BooleanField(default=False)),
                (
                    "exercise_name",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "exercise_start",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "exercise_deadline",
                    models.CharField(blank=True, max_length=64),
                ),
                ("is_online_session", models.BooleanField(default=False)),
                (
                    "online_session_name",
                    models.CharField(blank=True, max_length=128),
                ),
                (
                    "online_session_link",
                    models.CharField(blank=True, max_length=256),
                ),
                (
                    "online_session_status",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "online_session_start",
                    models.CharField(blank=True, max_length=64),
                ),
                (
                    "online_session_end",
                    models.CharField(blank=True, max_length=64),
                ),
                ("is_sent", models.BooleanField(default=False)),
                (
                    "lms_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="lms_public.lmscourse",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public_messages",
                        to="common.lmsuser",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_lms_interval_minutes",
                    models.PositiveIntegerField(default=5),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.lmsuser",
                    ),
                ),
            ],
        ),
    ]
